<!DOCTYPE html><!-- "' --></textarea></script></style></pre></xmp></a></audio></button></canvas></datalist></details></dialog></iframe></listing></meter></noembed></noframes></noscript></optgroup></option></progress></rp></select></table></template></title></video>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Server Error</title>
<meta http-equiv="refresh" content="3;URL='https://gamifactory.eu/'">
<style>
	#maintenance { all: initial; position: absolute; top: 0; left: 0; right: 0; height: 70vh; min-height: 400px; display: flex; align-items: center; justify-content: center; z-index: 1000 }
	#maintenance div { all: initial; max-width: 550px; background: white; color: #333; display: block }
	#maintenance h1 { all: initial; font: bold 50px/1.1 sans-serif; display: block; margin: 40px }
	#maintenance p { all: initial; font: 20px/1.4 sans-serif; margin: 40px; display: block }
	#maintenance small { color: gray }
</style>

<div id=maintenance>
	<div>
		<h1>Na webstránke sa pracuje.</h1>
	</div>
</div>

<script>
	document.body.insertBefore(document.getElementById('maintenance'), document.body.firstChild);
</script>
